#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logNet)
Q_DECLARE_LOGGING_CATEGORY(logOt)
Q_DECLARE_LOGGING_CATEGORY(logEditor)
Q_DECLARE_LOGGING_CATEGORY(logDocs)
Q_DECLARE_LOGGING_CATEGORY(logCursors)
Q_DECLARE_LOGGING_CATEGORY(logAuth)
